Update logstash.bat
elastic/logstash pull request #11069
Opened 2019-08-22 00:52 UTC by htatemura

Reported:
https://github.com/elastic/logstash/issues/10122

As Paulomart mentioned in below full request after merged, each classpath entry is wrapped in " anyways:
https://github.com/elastic/logstash/pull/9898

Not many users is using Windows version, but need to fix for those user.

2019-08-22 00:52 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2019-10-18 14:00 UTC, Paulomart commented
Can someone from the maintainers look at this? This is so annoying.

2019-12-31 10:42 UTC, kares requested changes
I think we should keep the quotes so that we do not go back and forth 
and instead handle the variable "quoted" so that it works in all cases :
```
:concat
if "%CLASSPATH%" == "" (
  set "CLASSPATH=%~1"
) else (
  set "CLASSPATH=%CLASSPATH%;%~1"
)
goto :eof
```
... if someone could test that out and make the changes we would :goal_net:

2019-12-31 10:42 UTC, kares commented on bin/logstash.bat
> +%JAVA% %JAVA_OPTS% -cp %CLASSPATH% org.logstash.Logstash %*
this will revert back and we potentially re-introduce issues fixed at https://github.com/elastic/logstash/pull/9898

2026-09-07 07:09 UTC, closed without merging