remove google java formatter dependency
elastic/logstash pull request #11765
Opened 2020-04-08 09:44 UTC by jsvd

2020-04-13 16:15 UTC, jsvd commented
@colinsurprenant you've been around the compilation code recently, what do you think here about the need of this dependency? if this is being used to avoid cache invalidation, in what scenarios does it do that?

This dependency was introduced in https://github.com/elastic/logstash/pull/8913/

2020-04-28 16:57 UTC, colinsurprenant commented
Good question, will investigate.

2020-09-02 21:30 UTC, colinsurprenant commented
@jsvd  This is used to do generated source code formatting and in that respect insures that 2 equivalent code generation will yield the same text+formatting. I see that the note about licensing :

> WARNING: DO NOT UPGRADE "google-java-format"
> later versions require GPL licensed code in javac-shaded that is
> Apache2 incompatible

I just verified that and starting at v1.8 they removed that GPL dependency  we should be good to upgrade to [latest v1.9 ](https://mvnrepository.com/artifact/com.google.googlejavaformat/google-java-format/1.9) without incompatible license dependency. 

I think we can close this and create a new PR to upgrade google-java-format.

2020-09-03 17:37 UTC, colinsurprenant commented
Created #12223 to upgrade to latest versions.

2020-09-03 17:42 UTC, jsvd commented
@colinsurprenant I believe that version only works with Java >= 9, which is why we didn’t upgrade

2020-09-03 18:10 UTC, colinsurprenant commented
Good catch. I can't find clear indications for the Java version requirements but looking at https://github.com/google/google-java-format/releases all I see is that v1.8 requires JDK 11. 

Short of upgrading the library because of minimum JDK requirements we can either keep the current version or remove it altogether as you suggest here but by doing so we also will loose readable formatting on the generated sources which is useful when developing/debugging. I don't think that removing the formatter will break caching but I don't know for sure.

2022-02-07 08:59 UTC, andsel commented
Here we should upgrade to [version 1.13](https://mvnrepository.com/artifact/com.google.googlejavaformat/google-java-format/1.13.0).

2022-02-07 09:02 UTC, andsel requested changes
Left a comment to update the version

2022-02-07 09:02 UTC, andsel commented on logstash-core/build.gradle
> -    implementation('com.google.googlejavaformat:google-java-format:1.1') {
Given that it's use for code formatting in debug mode of Janino, we should keep it and update to version 1.13 which still require Java 11 and is In Apache License

2022-02-07 11:06 UTC, jsvd commented
Closing this in favor of https://github.com/elastic/logstash/pull/13700

2022-02-07 11:06 UTC, closed without merging