enable converging state with predefined pipeline actions
elastic/logstash pull request #12582
Opened 2021-01-18 19:36 UTC by kaisecheng

Fixed: #12560
This PR allows the agent to converge state with predefined pipeline actions instead of fetching the full set of pipelines from elasticsearch and compute the pipeline actions internally. This opens a way for plugins to trigger pipeline termination. A usage is logstash-filter-geoip which needs to shut down its own pipeline in certain conditions.

2021-01-19 19:06 UTC, yaauie requested changes
I've left a few notes in-line.

I think we should attempt tp expose a simpler interface like `Agent#stop_pipeline(pipeline_id)`, instead of propagating the agent's internals like `LogStash::PipelineAction::*` to our plugins. When we increase the amount of internals our plugins need to know about, we prevent ourselves from later being able to change those internals.

There may be an argument for also implementing `Agent#reload_pipeline(pipeline_id)` along-side the above, even if we don't need it now, but I don't see a reason to add interfaces for the `delete` or `create` actions.

2021-01-19 23:22 UTC, kaisecheng commented
> I've left a few notes in-line.
> 
> I think we should attempt tp expose a simpler interface like `Agent#stop_pipeline(pipeline_id)`, instead of propagating the agent's internals like `LogStash::PipelineAction::*` to our plugins. When we increase the amount of internals our plugins need to know about, we prevent ourselves from later being able to change those internals.
> 
> There may be an argument for also implementing `Agent#reload_pipeline(pipeline_id)` along-side the above, even if we don't need it now, but I don't see a reason to add interfaces for the `delete` or `create` actions.

@yaauie I made the change as per request. I didn't implement `reload_pipeline` for the unknown future use case. It is great to have your early feedback. Let me know if you think `reload_pipeline` is necessary

2021-01-29 06:05 UTC, yaauie approved these changes
:tada:

LGTM.

Good work calling out the potential deadlock. We have an opportunity to bubble up that warning to the public function where it is more likely to be seen.

For now, this will do. Perhaps we can eventually eliminate the deadlock, but a rework of that magnitude is certainly beyond the scope of this PR.

2021-01-29 06:05 UTC, yaauie commented on logstash-core/lib/logstash/agent.rb
> +  def stop_pipeline(pipeline_id)
```suggestion
  ##
  # Shut down a pipeline and wait for it to fully stop.
  # WARNING: Calling from `Plugin#initialize` or `Plugin#register` will result in deadlock.
  # @param pipeline_id [String]
  def stop_pipeline(pipeline_id)
```

2021-01-29 13:29 UTC, merged