plugin manager uninstall plugin regardless of working directory
elastic/logstash pull request #12786
Opened 2021-03-30 16:35 UTC by kaisecheng

## Release notes

Fix: allow plugin manager to remove plugin regardless of the current working directory

## What does this PR do?

change the removal procedure from relative path to absolute path

## Why is it important/What is the impact to the user?

This PR fixes an issue that was preventing user uninstalls plugin from the plugin manager when user is not in $LOGSTASH_HOME directory

## Author's Checklist

- [x] tested in macOS

## How to test this PR locally

Assuming your Logstash is not installed in home directory
In mac
run uninstall command outside $LOGSTASH_HOME
> cd ~
> $LOGSTASH_HOME/bin/logstash-plugin remove logstash-filter-kv

terminal should show "Successfully removed logstash-filter-kv"

## Related issues

Closes #10781

2021-03-31 18:00 UTC, robbavey requested changes
It would be nice to have tests for this - we have existing tests (https://github.com/elastic/logstash/blob/master/qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb#L40 and https://github.com/elastic/logstash/blob/master/qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb#L40), but they are currently skipped. 
I did a quick commit on a test branch, reinstating the test (ignoring the text part for now), and it looks like the underlying issue they were skipped for is fixed - and your change does seem to fix the tests as advertised.

2021-04-05 16:12 UTC, roaksoax approved these changes
LGTM!

2021-04-05 16:45 UTC, robbavey commented
@kaisecheng The tests aren't run as part of standard CI - before committing can you push a new branch to the `elastic/logstash` repo and trigger a test manually from https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance/ using `build with parameters`, specifying your branch name in the parameters (you will need to login to jenkins to be able to do this).

2021-04-08 15:26 UTC, robbavey approved these changes
LGTM. Couple of nits on commented out code

2021-04-08 15:26 UTC, robbavey commented on qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
> +        # expect(result.stdout).to match(/^Removing logstash-filter-qatest/)
Can we either remove the commented out line, or make this work? I'm fine with either - the text test is somewhat fragile, and the 'not_to_have_installed?` test is sufficient

2021-04-08 15:46 UTC, robbavey approved these changes
LGTM

2021-04-08 15:59 UTC, merged