Update feature-request.md
elastic/logstash pull request #12873
Opened 2021-05-05 20:03 UTC by roaksoax

Update feature-request.md to provide a nicer description.

2021-05-05 20:12 UTC, karenzone requested changes
For consideration

2021-05-05 20:12 UTC, karenzone commented on .github/ISSUE_TEMPLATE/feature-request.md
> +about: Request a new feature or an enhancement of a current one
```suggestion
about: Request a new feature or suggest an enhancement to a existing one
```

2021-05-05 20:50 UTC, karenzone approved these changes
LGTM 🎉

2021-05-06 00:03 UTC, hendry-lim requested changes

2021-05-06 00:03 UTC, hendry-lim commented on .github/ISSUE_TEMPLATE/feature-request.md
> +about: Request a new feature or suggest an enhancement to a existing one
```suggestion
about: Request a new feature or suggest an enhancement to an existing one
```

2022-08-09 13:46 UTC, merged