Revert bundler version
elastic/logstash pull request #12910
Opened 2021-05-13 21:06 UTC by robbavey

Recent versions of bundler (> 2.2.3) have changed the resolution to resolve
for the specific running platform, using the specific platform triple, such
as `universal-java-1.8`, rather than `java`, as was previously the case, meaning
that the 'PLATFORMS` section of the `Gemfile.lock` will change from:

```
PLATFORMS
java
```

after:

```
PLATFORMS
universal-java-1.8
```

At runtime, unless bundler is run in frozen mode, this value is resolved again at
runtime, and depending on whether the platform being run in matches that being built
on, `Gemfile.lock` is resolved to match the running platform - which now causes a
runtime error when running Logstash as a service, as the running application no longer
has write permission on `Gemfile.lock` after #12782.

While this should fix #12818, we should look into a permanent solution to enable us to
keep up with bundler updates.

## Release notes

## What does this PR do?

## Why is it important/What is the impact to the user?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2021-05-13 22:47 UTC, yaauie approved these changes
LGTM📍(pending 💚)

2021-05-13 22:50 UTC, yaauie requested changes

2021-05-13 22:50 UTC, yaauie commented on build.gradle
> +      setupJruby(projectDir, buildDir.1.4)
```suggestion
      setupJruby(projectDir, buildDir)
```

2021-05-24 13:23 UTC, robbavey commented
@yauuie - ready for re-review

2021-08-18 19:13 UTC, robbavey commented
https://github.com/elastic/logstash/pull/13015 removes the need for this PR

2021-08-18 19:13 UTC, closed without merging