Release notes draft for 7.13.3
elastic/logstash pull request #13031
Opened 2021-06-29 16:00 UTC by logstashmachine

2021-06-30 11:50 UTC, jsvd commented on docs/static/releasenotes.asciidoc
> +
```suggestion

```

2021-06-30 11:50 UTC, jsvd commented on docs/static/releasenotes.asciidoc
> +* Fix: reduce error logging on connection resets https://github.com/logstash-plugins/logstash-input-beats/pull/424[#424]
```suggestion
* Fix: reduce error logging on connection resets https://github.com/logstash-plugins/logstash-input-beats/pull/424[#424]

```

2021-07-06 19:36 UTC, karenzone requested changes
Needs this fix to unresolvable link.

2021-07-06 19:36 UTC, karenzone commented on docs/static/releasenotes.asciidoc
> +* Changed jar dependencies to reflect newer versions https://github.com/logstash-plugins/logstash-input-http/pull/425[#425]
```suggestion
* Changed jar dependencies to reflect newer versions https://github.com/logstash-plugins/logstash-input-beats/pull/425[#425]
```

2021-07-06 20:19 UTC, karenzone commented
Link fixed in plugin repo: https://github.com/logstash-plugins/logstash-input-beats/pull/427

2021-07-06 20:19 UTC, karenzone approved these changes
Builds cleanly, links resolve correctly. LGTM

2021-07-07 10:31 UTC, merged