Release notes draft for 7.13.4
elastic/logstash pull request #13061
Opened 2021-07-09 16:31 UTC by logstashmachine

2021-07-09 17:12 UTC, karenzone approved these changes
LGTM

2021-07-13 13:26 UTC, andsel approved these changes
LGTM

Re-launched the tool release notes generator (`tools/release/generate_release_notes.rb 7.13 7.13.4`) and nothing changed.

2021-07-15 09:16 UTC, andsel requested changes
@karenzone yesterday was merged a bugfix for GeoIP, so it's the only change for `7.13.4`

2021-07-15 09:16 UTC, andsel commented on docs/static/releasenotes.asciidoc
> +No user-facing changes in Logstash core.
```suggestion
Fixed bug that sometimes happened when multiple pipelines with GeoIP filter tries to update the local database file. #13072
```

2021-07-16 22:40 UTC, karenzone commented
Thanks for adding the fixed issue, @andsel.  I accepted your suggestion, and added a link to the issue. 
I also added a PREVIEW link in the item description so that you can see how it renders.

2021-07-16 23:04 UTC, karenzone approved these changes
Thanks for adding the fixed issue, @andsel. I accepted your suggestion, and added a link to the issue.  I also added a PREVIEW link in the item description so that you can see how it renders. LGTM!

2021-07-20 07:07 UTC, andsel approved these changes

2021-07-20 07:08 UTC, merged