Doc: Add note and example for date math in conditionals
elastic/logstash pull request #13199
Opened 2021-09-01 23:24 UTC by karenzone

## Release notes
[rn:skip] 

## What does this PR do?
Updates docs with info about date math in conditionals and provides a workaround example.
Brings topic up to current documentation standards for heading capitalization and tagging

2021-09-10 16:35 UTC, robbavey reviewed
I like the comment, couple of questions on content and positioning of this section

2021-09-10 16:35 UTC, robbavey commented on docs/static/configuration.asciidoc
> +[discrete]
I like the content, but I think positionally, we might want to put this under the `@metadata` section - the workaround uses the `@metadata` field, and the context could be useful. Also, I suspect that this topic is _probably_  less relevant to more users than the `@metadata` topic

2021-09-10 16:35 UTC, robbavey commented on docs/static/configuration.asciidoc
> +`if "%{+HH}:%{+mm}" < "15:30" {`
Maybe add the 

`add_field => {"string_compare" => "%{+HH}:%{+mm} is before 15:30"}`

part to this the broken example to give an equivalence between the working and non-working versions?

2021-09-10 16:35 UTC, robbavey commented on docs/static/configuration.asciidoc
> +Date math in conditionals is not currently supported, but a workaround is available.
If we put this content below `@metadata`, maybe we can refer to it here, stating something like "a workaround using the `@metadata` field is available"

Unless that is a bit long winded and unnecessary detail

2021-09-14 16:07 UTC, karenzone commented
Good review comments, @robbavey. They're in.

2021-09-14 16:27 UTC, robbavey commented on docs/static/configuration.asciidoc
> +Another use case is the https://github.com/logstash-plugins/logstash-input-couchdb_changesCouchDB[Changes input plugin].
Link to plugin is broken

2021-09-14 16:27 UTC, robbavey commented on docs/static/configuration.asciidoc
> +===== Date math in conditionals
Maybe this should be `sprintf time format`?

2021-09-14 16:27 UTC, robbavey commented on docs/static/configuration.asciidoc
> +NOTE: Date math in conditionals is not currently supported.
Maybe more appropriate as `sprintf time format` - `Date math` is more typically an Elasticsearch term

2021-09-14 16:27 UTC, robbavey commented on docs/static/configuration.asciidoc
> +This statement won't work:
I think a little more context would help here:

Something like:

This attempt to use add a field depending on the ingestion time won't work using `sprintf time format` directly

2021-09-20 18:33 UTC, robbavey commented on docs/static/configuration.asciidoc
> +  }
Nit: formatting

2021-09-20 18:33 UTC, robbavey commented on docs/static/configuration.asciidoc
> +    }
Nit: formatting

2021-09-20 18:34 UTC, robbavey requested changes
Couple of formatting nitpicks.

2021-09-21 18:10 UTC, robbavey approved these changes
LGTM

2021-09-21 19:09 UTC, merged