[Docs] Add pipeline.ecs_compatibility to the list
elastic/logstash pull request #13612
Opened 2022-01-13 09:07 UTC by toby-sutor

Adding the `pipeline.ecs_compatibility` setting from https://www.elastic.co/guide/en/logstash/current/ecs-ls.html and https://github.com/elastic/logstash/blob/7.16/logstash-core/lib/logstash/runner.rb#L163 to the list of available command line options. This is important because with 7.16 this will lead to a lot of deprecation logging like 
````
Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.
````

2022-01-14 15:09 UTC, yaauie requested changes
Thank you for calling this missing edge out.

While this command-line flag works to set the top-level `pipeline.ecs_compatibility` setting (overwriting that found in the `config/logstash.yml`), I think our users will get more value out of handling this as a pipeline setting so we want to be consistent in our docs calling out that path as preferred.

I'm also flagging @karenzone for a docs-oriented review of both your contribution and my suggested alternate.

2022-01-14 15:09 UTC, yaauie commented on docs/static/running-logstash-command-line.asciidoc
> +  The default depends on the individual plugins.
I'm adapting the text we have for the [`pipeline.ecs_compatibility`](https://github.com/elastic/logstash/blob/70fb72b584d08600d4cb1d08c6f4e31e9b572a07/config/logstash.yml#L69-L81) config file option.

```suggestion
  Sets the process default value for  ECS compatibility mode.
  Can be an ECS version like `v1` or `v8`, or `disabled`.
  The default is `v8`.
  Pipelines defined before Logstash 8 operated without ECS in mind.
  To ensure a migrated pipeline continues to operate as it did in older releases of Logstash, opt-OUT of ECS for the individual pipeline by setting `pipeline.ecs_compatibility: disabled` in its `pipelines.yml` definition.
  Using the command-line flag will set the default for _all_ pipelines, including new ones.
  See <<ecs-compatibility>> for more info.
```

2022-01-18 15:53 UTC, karenzone approved these changes
LGTM. Thank you!

2022-01-19 00:36 UTC, yaauie approved these changes

2022-01-19 00:37 UTC, merged