Removal of sys-v init.d scripts
elastic/logstash pull request #13922
Opened 2022-03-22 16:50 UTC by roaksoax

## Release notes

## What does this PR do?

This PR drops the installation of the sys-v init.d scripts and drops the testing of Logstash in oel-6. This were left overs of dropping support for CentOS-6.

This aligns with other products, such as Elasticsearch, which no longer ship sys-v init scripts.

## Why is it important/What is the impact to the user?

Users will now solely rely on systemd units to run the logstash service for RPM/Deb packages, as all of the currently supported Operating Systems are systemd based.

2022-03-22 19:13 UTC, roaksoax commented
Failure seems unrelated. Jenkins test this please./

2022-03-24 14:17 UTC, roaksoax commented
Jenkins test this please

2022-03-24 14:23 UTC, roaksoax commented
Jenkins test this please

2022-03-30 13:14 UTC, jsvd requested changes
There are multiple places both in code and docs where we still mention the init.d script:

```
❯ grep "init.d" . -r
Binary file ./jdk/lib/modules matches
./qa/rspec/commands/suse/sles-11.rb:        cmd = sudo_exec!("/etc/init.d/#{package} status")
./qa/rspec/commands/suse/sles-11.rb:        sudo_exec!("/etc/init.d/#{service} #{action}")
./docs/static/running-logstash.asciidoc:sudo /etc/init.d/logstash start
./docs/static/running-logstash.asciidoc:The auto-generated configuration file for SysV systems is `/etc/init.d/logstash`.
./docs/static/shutdown.asciidoc:/etc/init.d/logstash stop
Binary file ./.git/index matches
./pkg/service_templates/sysv/etc/init.d/logstash:  logger -t "/etc/init.d/logstash" "$@"
./pkg/debian/before-remove.sh:  elif [ -r "/etc/init.d/logstash" ]; then
./pkg/debian/before-remove.sh:    if [ -f "/etc/init.d/logstash" ]; then
./pkg/debian/before-remove.sh:      rm /etc/init.d/logstash
./pkg/centos/before-remove.sh:  elif [ -r "/etc/init.d/logstash" ]; then
./pkg/centos/before-remove.sh:    if [ -f "/etc/init.d/logstash" ]; then
./pkg/centos/before-remove.sh:      rm /etc/init.d/logstash
./pkg/ubuntu/before-remove.sh:  elif [ -r "/etc/init.d/logstash" ]; then
./pkg/ubuntu/before-remove.sh:    if [ -f "/etc/init.d/logstash" ]; then
./pkg/ubuntu/before-remove.sh:      rm /etc/init.d/logstash
```

We should address these before merging.

2022-03-30 14:17 UTC, roaksoax commented
@jsvd I've addressed the changes in the docs only, provided that everything else is as intended.

- ./qa/rspec/commands/suse/sles-11.rb - sles-11 is not being tested, and as such, this should be inspected and evaluated as part of the roadmap item (which we already have). AS such, not going to make any chances in this branch.
- pkg/* - Everything that does here is as expected.

2022-03-30 14:49 UTC, roaksoax commented
Jenkins test this again

2022-03-30 14:51 UTC, jsvd commented on rakelib/artifacts.rake
>      File.join(basedir, "pkg", "service_templates", "sysv", "etc", "default", "logstash").tap do |path|
@roaksoax should we also remove this one?

2022-03-30 14:58 UTC, jsvd approved these changes
LGTM

2022-03-30 15:26 UTC, merged

2022-03-30 15:49 UTC, roaksoax commented
@logstashmachine backport 8.2