[doc] Update example ES output configs to reflect DataStreams being d…
elastic/logstash pull request #14011
Opened 2022-04-21 14:24 UTC by roaksoax

…efault

## Release notes

## What does this PR do?

## Why is it important/What is the impact to the user?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2022-04-25 22:29 UTC, karenzone commented on docs/static/filebeat-modules.asciidoc
> +enabled by default starting from 8.0.
```suggestion
<1> If you are disabling the Data Streams in your configuration, set the `index` option to `%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}` instead.
Data streams are
enabled by default.
```

2022-04-25 22:38 UTC, karenzone reviewed
Nice changes. This approach will help users quickly see the differences with and without data streams. 

I left comments inline for consideration.
Note: I reviewed docs, but I did not validate the Logstash implementation.

2022-04-25 22:38 UTC, karenzone commented on docs/static/filebeat-modules.asciidoc
> +enabled by default starting from 8.0.
Each minor revision has its own complete doc set (8.2, 8.1, 8.0, 7.17, etc.) that can easily be referenced. For that reason, we don't usually put version numbers in our content.  In the 8.3 version of the guide, saying that data streams are enabled is enough.

2022-04-25 22:38 UTC, karenzone commented on docs/static/filebeat-modules.asciidoc
>  passed in the event.
```suggestion
<2> Configures {ls} to select the correct ingest pipeline based on metadata
passed in the event.
```

2022-04-25 22:38 UTC, karenzone commented on docs/static/filebeat-modules.asciidoc
> +enabled by default starting from 8.0.
Elastic standard for data streams is lower case and treated as plural.

2022-07-25 15:38 UTC, karenzone requested changes
LGTM

2022-07-25 15:40 UTC, karenzone approved these changes

2022-07-25 17:13 UTC, merged

2022-07-25 17:13 UTC, roaksoax commented
@logstashmachine backport 8.4

2022-07-25 17:35 UTC, roaksoax commented
@logstashmachine backport 8.3