Fix queue size calculation to include whole size of tail pages
elastic/logstash pull request #14153
Opened 2022-05-24 15:14 UTC by kaisecheng

## Release notes

Fix persistent queue size calculation to include whole size of tail pages

## What does this PR do?

This commit uses the capacity of tail pages to do size calculation. 
Every page is initialized with its full capacity, default 64mb. Prior to the change, it counts the size of the events per tail page and the head page. Some pages may have 100kb event, some may have 30mb. Tail pages are immutable and consume a fixed size on disk. So, the size calculation should take the capacity not the event size. Logstash use this size to determine if the queue is full.

## Why is it important/What is the impact to the user?

User relies on queue.max_bytes to control the total queue size. Under the old calculation, queue size can exceed the setting. 
This also changes the metrics in monitoring API /_node/stats `pipelines.main.queue.queue_size_in_bytes`

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Closes: #14566 

## Use cases

## Screenshots

## Logs

2022-06-14 13:17 UTC, andsel requested changes
The changes is good however left a note a provide better meaning for something that seems like a magic number

2022-06-14 13:17 UTC, andsel commented on logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
> +            assertThat(queue.getPersistedByteSize(), is(1243L));
I think that the `1243` sounds like a magic number.
Please add a comment that describe the above explanation or extract in a variable like:
```ruby
expected_size = num_pages * page_size + head_page_size
```

2024-03-13 11:59 UTC, kaisecheng commented
Abandoned this PR as it has different assumption on how the queue size should calculate.

In the doc, [garbage collection](https://www.elastic.co/guide/en/logstash/current/persistent-queues.html#garbage-collection), `Each page containing unprocessed events will count against the queue.max_bytes byte size.`, while this PR counts total pages size with their max capacity. 

The issue of PQ could exceed queue.max_bytes is still here. We can keep the current calculation for queue.max_bytes (only count unprocessed events) and add a function to ensure the total bytes on disk respects the limit max bytes

2024-03-13 11:59 UTC, closed without merging

2024-03-13 12:09 UTC, kaisecheng commented on logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
> +                    + tailPages.stream().mapToLong(p -> p.getPageIO().getCapacity()).sum();
The PR was on hold as I noticed the change will break assumption of the metrics related to queue size, and was not clear if we have well defined how max queue size should calculate.

Close this and will find another way to fix the issue.