Release Notes for 8.3.1
elastic/logstash pull request #14311
Opened 2022-06-28 21:10 UTC by robbavey

No user facing changes in this release

2022-06-28 21:12 UTC, kilfoyle approved these changes
LGTM! 🚀

2022-06-29 13:43 UTC, kaisecheng commented on docs/static/releasenotes.asciidoc
> +We recommend not upgrading to Logstash 8.3.0 if you are using the dead letter queue.
should we also mention persistent queue?

2022-06-29 14:32 UTC, jsvd requested changes

2022-06-29 14:32 UTC, jsvd commented on docs/static/releasenotes.asciidoc
> +We recommend not upgrading to Logstash 8.3.0 if you are using the dead letter queue.
```suggestion
We recommend not upgrading to Logstash 8.3.0 if you are using Dead Letter or Persistent Queues.
```

2022-06-29 14:32 UTC, jsvd commented on docs/static/releasenotes.asciidoc
> +An event serialization bug was discovered, which causes an issue when trying to read dead letter queues created
```suggestion
An event serialization bug was discovered, which causes an issue when trying to read Dead Letter or Persistent Queues created
```

2022-06-29 20:39 UTC, kilfoyle commented on docs/static/releasenotes.asciidoc
> +An event serialization bug was discovered, which causes an issue when trying to read Dead Letter or Persistent Queues created
```suggestion
An event serialization bug was discovered, which causes an issue when trying to read dead letter or persistent queues created
```

2022-06-29 20:39 UTC, kilfoyle commented on docs/static/releasenotes.asciidoc
> +We recommend not upgrading to Logstash 8.3.0 if you are using Dead Letter or Persistent Queues.
```suggestion
We recommend not upgrading to Logstash 8.3.0 if you are using dead letter or persistent queues.
```

2022-06-29 20:57 UTC, jsvd commented on docs/static/releasenotes.asciidoc
> +  If you're using dead letter queue we recommend that you do not use Logstash 8.3.0 and upgrade to 8.3.1.
```suggestion
  If you're using dead letter queues or persistent queues we recommend that you do not use Logstash 8.3.0 and upgrade to 8.3.1.
```

2022-06-29 20:59 UTC, jsvd approved these changes
LGTM

2022-06-29 21:14 UTC, merged

2022-06-30 07:43 UTC, andsel commented
I think this should be forward ported to `main` branch