Bumped SnakeYaml to 2.0
elastic/logstash pull request #14948
Opened 2023-03-08 06:06 UTC by deepakLabs

## Release notes
Bumped Snakeyaml to 2.0

## What does this PR do?
PR updates the snakeyaml version to 2.0

## Why is it important/What is the impact to the user?
Removes heavily vulnerable snakeyaml 1.33 and updates to latest 2.0

## Checklist

- [ ] ~~My code follows the style guidelines of this project~~
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

## How to test this PR locally

## Related issues

2023-03-08 06:06 UTC, logstashmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2023-03-08 11:34 UTC, deepakLabs commented
Have signed the Contributor Agreement

2023-03-08 11:35 UTC, deepakLabs commented
Hello @roaksoax, CLA has been signed

2023-03-08 11:39 UTC, deepakLabs commented
@Jenkins Please test this

2023-03-09 09:21 UTC, andsel requested changes
For reasons to investigate the task:
```sh
./gradlew clean installBundler
``` 
fails with 
```sh
> Task :installBundler
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:632: warning: The Psych YAML extension failed to load.
Check your env for conflicting versions of SnakeYAML
See https://github.com/jruby/jruby/wiki/FAQs#why-does-the-psych-yaml-extension-fail-to-load-in-my-environment

> Task :installBundler FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home/andrea/workspace/logstash_andsel/rubyUtils.gradle' line: 101

* What went wrong:
Execution failed for task ':installBundler'.
> (LoadError) bad SnakeYAML version 2.0, required 1.21 or higher; check your CLASSPATH for a conflicting jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
49 actionable tasks: 35 executed, 14 up-to-date
```

2023-04-24 07:01 UTC, deepakLabs commented
@andsel Can you assign it to someone who has bandwidth to look into this?

2023-04-24 12:47 UTC, mashhurs commented
@deepakLabs thanks for the contribution.
We will prioritize and start working on this soon (will update once I start).
However, simply upgrading to `2.0` doesn't work as I saw [number of changes in `snakeyaml` changelog](https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes), also proceeded simple test with `useragent` plugin where changes broke.
I have two BIG concerns:
- `SafeConstructor ignores LoaderOptions setCodePointLimit()` changelog: when we upgraded to `1.33` we set code point limit and now it ignores in `2.0`. We have to make sure our sources are [CVE free](https://www.cvedetails.com/cve/CVE-2022-38752).
- `CustomClassLoaderConstructor takes LoaderOptions`: when creating `Yaml` interface, we have some places utilize `CustomClassLoaderConstructor` and now it requires `LoaderOptions`.
- test rest of fix changes

2023-05-22 05:05 UTC, deepakLabs commented
@mashhurs , Can we include it in the current sprint cycle?

2023-05-22 05:27 UTC, mashhurs commented
> @mashhurs , Can we include it in the current sprint cycle?

We would really love!
We are planning to start this mid of next month if every task goes as planned.

2023-06-09 05:55 UTC, deepakLabs commented
@mashhurs Please add this one in the sprint

2023-06-09 14:09 UTC, rheironimus commented
@mashhurs @deepakLabs  Is this fix in progress and if so, do you have an idea of a timeline for a release?  Or do you need assistance?  My team has an interest in getting this resolved quickly and can contribute if not already underway.  Thanks!

2023-06-09 14:42 UTC, mashhurs commented
> @mashhurs @deepakLabs Is this fix in progress and if so, do you have an idea of a timeline for a release? Or do you need assistance? My team has an interest in getting this resolved quickly and can contribute if not already underway. Thanks!

We have this planned but not started yet. A contribution will be highly appreciated.

2023-06-09 15:08 UTC, mashhurs commented
> @mashhurs Hi there - I'm part of the team that @rheironimus mentioned above - I don't see an associated issue for this work, does one need creating and assigning before we can start contributing?

Creating an issue and providing details (especially internal details like addresses the [possible concerns](https://github.com/elastic/logstash/pull/14948#issuecomment-1520092365)) would be really great.
Thank you so much!

2023-06-11 07:05 UTC, deepakLabs commented
@rheironimus I would also appreciate someone taking an active role in this pr request, I currently don't have a technical expertise or team that would help me here.

2023-06-12 10:27 UTC, JonahLuckett commented
Fab fab - will get an issue made today and get started on the work

2023-06-13 10:37 UTC, JonahLuckett commented
Created the issue [here](https://github.com/elastic/logstash/issues/15088) - could someone please assign me to this work? @mashhurs potentially?

2023-06-13 13:35 UTC, mashhurs commented
> Created the issue [here](https://github.com/elastic/logstash/issues/15088) - could someone please assign me to this work? @mashhurs potentially?

Done! Thank you!

2023-06-29 14:35 UTC, roaksoax commented
We've bumped snakeyaml to 2.0 in [the following PR](https://github.com/elastic/logstash/pull/15125/files) , which is part of the [Jruby 9.4 work](https://github.com/elastic/logstash/pull/14861/files), and this change will be available in Logstash 8.10

2023-06-29 14:35 UTC, closed without merging