[WIP] Changed shutdown stalled method to check inflight and stalling length
elastic/logstash pull request #15056
Opened 2023-05-22 07:43 UTC by edmocosta

## Release notes

## What does this PR do?

## Why is it important/What is the impact to the user?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2023-05-24 14:18 UTC, edmocosta commented
Jenkins test this please

2023-05-26 10:33 UTC, jsvd requested changes
so here we're addressing the fact that if both counts and threads are empty then we don't want to mark the pipeline as stalled.

Separately, it is reasonable to mark the pipeline as stalled. Either:
a) there are no inflight events but there are still threads executing. OR:
b) there are inflight events but no stalling threads

Both of these should be rare, but they are real justifications for the pipeline not shutting down.

So I'd suggest changing the logic to mark the pipeline as stalled iff:
1. the number of inflight events is not decreasing and > 0, or
2. number of stalling threads is > 0

Either if these is enough to mark as stalled, or both.

Writing tests for these scenarios will help:
a) 5 reports with 0 inflight events + no stalled threads => not stalled
b) 5 reports with 0 inflight events + stalled threads => stalled
c) 5 reports with > 0 inflight events + no stalled threads => stalled
c) 5 reports with > 0 inflight events + stalled threads => stalled

2023-05-30 11:20 UTC, jsvd requested changes
we should have a couple of tests for when inflight count is always 0 on all 5 reports. 
also added a few comments about the logic

2023-05-30 11:20 UTC, jsvd commented on logstash-core/src/main/java/org/logstash/execution/ShutdownWatcherExt.java
> +import java.util.concurrent.atomic.AtomicInteger;
If possible I'd prefer not to have changes in the imports unless they're necessary.

2023-05-30 11:20 UTC, jsvd commented on logstash-core/src/main/java/org/logstash/execution/ShutdownWatcherExt.java
> +        }
Given that these are derived from the reports array which is guaranteed to be of size `reportEvery`, these arrays should also be of size `reportEvery` (5)

2023-05-30 11:20 UTC, jsvd commented on logstash-core/src/main/java/org/logstash/execution/ShutdownWatcherExt.java
> +                : context.fals;
if all inflight counts are 0, then we look at `stallingthreads`, but that will always have a length of 5, so it's always true. We'd have to look at the last element of that array instead

2023-06-07 16:09 UTC, jsvd requested changes
the test failure is legit since it needs to now address the existance of a @thread, which in the test is likely to be nil

2023-06-19 09:11 UTC, jsvd approved these changes
minor nitpick, otherwise LGTM

2023-06-20 12:48 UTC, merged

2023-07-13 12:27 UTC, essodjolo commented
Hi @jsvd,

I have a user waiting for this fix. They reported that the issue is still happening in `8.8.2`. Can you confirm which version will embed this fix please?
Thanks.

Ps: I couldn't see any label pointing to the target version.

2023-07-17 10:07 UTC, jsvd commented
@logstashmachine backport 7.17

2023-07-17 10:07 UTC, jsvd commented
@logstashmachine backport 8.9

2023-07-17 10:18 UTC, jsvd commented
@logstashmachine backport 8.9