Update versions used in plugins CI
elastic/logstash pull request #15061
Opened 2023-05-24 07:31 UTC by andsel

**Merge after DRA build of 8.8.1**

Updated Logstash versions used in CI

2023-05-24 08:14 UTC, jsvd requested changes

2023-05-24 08:14 UTC, jsvd commented on ci/logstash_releases.json
> +    "8.x": "8.8.1-SNAPSHOT"
Let's have plugins test against the next minor instead:

```suggestion
    "8.x": "8.9.0-SNAPSHOT"
```

2023-05-24 08:31 UTC, jsvd approved these changes
LGTM

2023-05-25 11:17 UTC, andsel commented
Jenkins test this please

2023-05-26 06:21 UTC, andsel commented
Jenkins test this please

2023-05-26 07:07 UTC, merged