Doc:
elastic/logstash pull request #15225
Opened 2023-07-31 22:44 UTC by karenzone

Related: 
* Issue #15172

Adds conceptual and "how to" info for Logstash Ingest pipelines. This doc is the conceptual counterpart to the `logstash-filter-elastic_integration` docs that focus on configuration and settings.

2023-07-31 22:59 UTC, karenzone commented on docs/static/ls-ingest-pipeline.asciidoc
> +As with other plugins, you can set up ingest pipelines at the {ls} level in {logstash-ref}/logstash-settings-file.html[`logstash.yml`], or at the pipeline level in {logstash-ref}/pipelines.yml[`pipel
```suggestion
As with other plugins, you can set up ingest pipelines at the {ls} level in {logstash-ref}/logstash-settings-file.html[`logstash.yml`], or at the pipeline level in {logstash-ref}/logstash-settings-file.html[`pipelines.yml`]. 
```

2023-08-07 18:31 UTC, karenzone commented on docs/static/ls-ingest-pipeline.asciidoc
> +// ToDo: Add link to published plugin for settings and additional instructions.
```suggestion
// ToDo: Add link to plugin doc for settings and additional instructions after those docs are published.
```

2023-08-11 22:03 UTC, karenzone commented
Hi @yaauie. Here's the initial conceptual content based on your EAH presentation and our Q&A session. (Thank you!) Please take a look and let me know what you think.

2023-08-23 20:29 UTC, karenzone commented
@yaauie, will you please take a look at what we have so far to be sure we're on the right track and to determine what else is needed?

2023-09-21 17:29 UTC, karenzone commented
Hi @flexitrev.  Here's the PR we discussed earlier. Looking forward to your feedback.

2023-09-21 17:43 UTC, flexitrev requested changes
We should overhaul what we are saying about this in the big picture. Logstash running ingest pipelines is a huge capability, but our primary use case is supporting Integrations through Logstash. Customers will certainly see the potential of this, and push it to the limit, but in our documentation we want to steer them to integrations because of the superior user experience.

2023-10-23 15:36 UTC, karenzone commented
@elasticmachine run elasticsearch-ci/docs

2023-11-01 22:01 UTC, closed without merging

2023-11-01 22:01 UTC, karenzone commented
Replaced by #15518