Doc: Update extending integrations docs to point to plugin
elastic/logstash pull request #15747
Opened 2024-01-05 00:35 UTC by karenzone

Fixes: #15740 
Topic: https://www.elastic.co/guide/en/logstash/master/ea-integrations.html

* Updates the feature docs to link to the plugin docs rather than the plugin repo
* Add ECS compliance to list of benefits of starting with an integration

2024-01-05 17:13 UTC, flexitrev requested changes
Can we let customers know what will happen or why the elastic integration filter needs to be the first filter? We also might suggest that preprocessing could be done in a separate pipeline (link logstash to logstash integration details)

2024-01-05 17:13 UTC, flexitrev commented on docs/static/ea-integrations.asciidoc
> +Create a {ls} pipeline that uses the <<plugins-inputs-elastic_agent,elastic_agent input>> plugin, and the <<plugins-filters-elastic_integration,elastic_integration filter>> plugin as the _first_ filt
What happens if this is not the first filter?

2024-01-25 15:34 UTC, flexitrev approved these changes
Looks good!

2024-01-25 16:02 UTC, merged

2024-01-25 16:04 UTC, karenzone commented
@logstashmachine backport 8.12

2024-01-25 16:05 UTC, karenzone commented
@logstashmachine backport 8.11

2024-01-25 16:05 UTC, karenzone commented
Backporting to 8.11 to fix an error in plugin name