add modules deprecation log for netflow, fb_apache and azure
elastic/logstash pull request #16529
Opened 2024-10-10 15:51 UTC by kaisecheng

This PR will be backported to 8.x

## Release notes

Add deprecation logs for modules netflow, fb_apache and azure

## What does this PR do?

Updated the deprecation log to send a clear message that netflow, fb_apache and azure modules will be removed in next major update.

## Why is it important/What is the impact to the user?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [x] run `bin/logstash --modules azure` and the updated deprecation msg is shown in logstash-deprecation.log
- [x] `bin/logstash --modules arcsight` does not show deprecation msg
- [x] run `bin/logstash` with the following logstash.yml show deprecation msg
```yaml
modules:
  - name: netflow
```  

## How to test this PR locally

## Related issues

- relates: https://github.com/elastic/logstash/issues/16357

## Use cases

## Screenshots

## Logs

2024-10-10 16:40 UTC, elasticmachine commented
## :yellow_heart: Build succeeded, but was flaky
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1617)
* Commit: fd2044d58779ad4e475e88a394cb051a17bb1c0f

### Failed CI Steps
* [:rspec: Ruby unit tests](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1617#01927721-5dcc-482d-92b5-6d74eed01f3a)
* [:rspec: Ruby unit tests](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1617#01927730-71ca-46a8-9a36-528377ddcade)

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1617","number":1617,"commit":"fd2044d58779ad4e475e88a394cb051a17bb1c0f"}],"number":1617}
buildkite-pr-comment-->

2024-10-11 12:30 UTC, andsel requested changes
I think that this PR should target directly the `8.x` if on the `main` we remove those modules

2024-10-11 16:17 UTC, kaisecheng commented
@andsel I think every PR is better to merge to main first than backport if possible. It can help tracing back the changes.

2024-10-11 20:17 UTC, closed without merging

2024-10-11 20:37 UTC, kaisecheng commented
created another PR against 8.x https://github.com/elastic/logstash/pull/16548