Introduce a new flag setting 'legacy.monitoring.enabled' which eventu…
elastic/logstash pull request #16586
Opened 2024-10-18 14:46 UTC by andsel

Introduce a new flag setting 'legacy.monitoring.enabled' which eventually enable the legacy monitoring collector

## Release notes

## What does this PR do?

## Why is it important/What is the impact to the user?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2024-10-18 15:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1724)
* Commit: 54bbe7da1db636ad5a74475129cbe2658b8117bd

cc @andsel

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1724","number":1724,"commit":"54bbe7da1db636ad5a74475129cbe2658b8117bd"}],"number":1724}
buildkite-pr-comment-->

2024-10-18 16:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1726)
* Commit: 6bd75a6b459fc7aa11603f461a4be6a4a9bc0c50

### History
* :green_heart: [Build #1724](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1724) succeeded 54bbe7da1db636ad5a74475129cbe2658b8117bd

cc @andsel

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1726","number":1726,"commit":"6bd75a6b459fc7aa11603f461a4be6a4a9bc0c50"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1724","number":1724,"commit":"54bbe7da1db636ad5a74475129cbe2658b8117bd"}],"number":1726}
buildkite-pr-comment-->

2024-10-21 10:20 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1729)
* Commit: 8fd24d295e3c39fcb7398421658917e8127825a3

### History
* :green_heart: [Build #1726](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1726) succeeded 6bd75a6b459fc7aa11603f461a4be6a4a9bc0c50
* :green_heart: [Build #1724](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1724) succeeded 54bbe7da1db636ad5a74475129cbe2658b8117bd

cc @andsel

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1729","number":1729,"commit":"8fd24d295e3c39fcb7398421658917e8127825a3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1726","number":1726,"commit":"6bd75a6b459fc7aa11603f461a4be6a4a9bc0c50"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1724","number":1724,"commit":"54bbe7da1db636ad5a74475129cbe2658b8117bd"}],"number":1729}
buildkite-pr-comment-->

2024-10-22 01:11 UTC, kaisecheng reviewed
Besides the suggestion of renaming the flag, I would suggest to add `allow.legacy.monitoring` to env2yaml.go. The main reason is to ease the transition for docker users as they can setup monitoring by just passing the env variable today.

2024-10-22 11:28 UTC, kaisecheng requested changes
please add the flag to [benchmark buildkite](https://github.com/elastic/logstash/blob/main/.buildkite/scripts/benchmark/config/logstash.yml#L6) 🙏 

When I use the xpack.* to enable monitoring in old way, Logstash does not give any hints/ logs that it is missing the flag. I think we need to print logs to guide user.

Let @karenzone to have a look on the words, otherwise, LGTM

2024-10-22 11:34 UTC, kaisecheng commented
One more missing in [default_metadata.rb](https://github.com/elastic/logstash/blob/main/logstash-core/lib/logstash/api/commands/default_metadata.rb#L73-L76) for `curl localhost:9600/`

2024-10-22 12:31 UTC, andsel commented
Thanks @kaisecheng for your review, added the allow.legacy.monitoring flag to BK pipeline and now logs a warn when legacy monitoring is enabled and not allowed.

Example of line logged:
```
[2024-10-22T14:27:17,977][WARN ][logstash.monitoringextension.pipelineregisterhook] Legacy internal monitoring is enabled (xpack.monitoring.enabled or monitoring.enabled is true) but not allowed. Please check your configuration and eventually set allow.legacy.monitoring
```

2024-10-22 12:57 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1736)
* Commit: 485d37fe37719f27cddc6dae481815e4b93e0670

### History
* :green_heart: [Build #1733](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1733) succeeded 9929323c98d0c813b1e984e8b5f70a7a5bd9f04d
* :green_heart: [Build #1729](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1729) succeeded 8fd24d295e3c39fcb7398421658917e8127825a3
* :green_heart: [Build #1726](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1726) succeeded 6bd75a6b459fc7aa11603f461a4be6a4a9bc0c50
* :green_heart: [Build #1724](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1724) succeeded 54bbe7da1db636ad5a74475129cbe2658b8117bd

cc @andsel

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1736","number":1736,"commit":"485d37fe37719f27cddc6dae481815e4b93e0670"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1733","number":1733,"commit":"9929323c98d0c813b1e984e8b5f70a7a5bd9f04d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1729","number":1729,"commit":"8fd24d295e3c39fcb7398421658917e8127825a3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1726","number":1726,"commit":"6bd75a6b459fc7aa11603f461a4be6a4a9bc0c50"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1724","number":1724,"commit":"54bbe7da1db636ad5a74475129cbe2658b8117bd"}],"number":1736}
buildkite-pr-comment-->

2024-10-22 13:31 UTC, kaisecheng reviewed
> One more missing in [default_metadata.rb](https://github.com/elastic/logstash/blob/main/logstash-core/lib/logstash/api/commands/default_metadata.rb#L73-L76) for `curl localhost:9600/`

☝️ Almost there

2024-10-22 13:31 UTC, kaisecheng commented on x-pack/lib/monitoring/monitoring.rb
> +          logger.warn("Legacy internal monitoring is enabled (xpack.monitoring.enabled or monitoring.enabled is true) but not allowed. Please check your configuration and eventually set allow.legacy.
```suggestion
          logger.warn("You have enabled legacy internal monitoring. However, starting from version 9.0, this feature is deactivated and behind a feature flag. Set `allow.legacy.monitoring` to `true` to allow access to the feature.)
```

2024-10-22 13:41 UTC, andsel commented
@kaisecheng 

> ☝️ Almost there

was fixed in https://github.com/elastic/logstash/pull/16586/files#diff-a0255510e1f939e6ad6e719d7db5ec42a9f0e886171561b1084da93693a44256R6  if I'm not wrong

2024-10-22 13:52 UTC, kaisecheng commented
@andsel https://github.com/elastic/logstash/blob/main/logstash-core/lib/logstash/api/commands/default_metadata.rb#L73-L76
It is about logstash API. When `enabled_xpack_monitoring?` is enabled, monitoring related info will return. I think it needs to add `&& LogStash::SETTINGS.get("allow.legacy.monitoring")`

2024-10-22 13:54 UTC, kaisecheng commented
@andsel btw, I have triggered exhausted test for this pr, but got [red](https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/845)

2024-10-23 07:51 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1745)
* Commit: 2e90f147c6eab93f0e5123ec9b2f4cb31cd0babe

### History
* :broken_heart: [Build #1737](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1737) failed cb91379caad315c23e20e0a80349e05ea6ef3fbd
* :green_heart: [Build #1736](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1736) succeeded 485d37fe37719f27cddc6dae481815e4b93e0670
* :green_heart: [Build #1733](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1733) succeeded 9929323c98d0c813b1e984e8b5f70a7a5bd9f04d
* :green_heart: [Build #1729](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1729) succeeded 8fd24d295e3c39fcb7398421658917e8127825a3
* :green_heart: [Build #1726](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1726) succeeded 6bd75a6b459fc7aa11603f461a4be6a4a9bc0c50

cc @andsel

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1745","number":1745,"commit":"2e90f147c6eab93f0e5123ec9b2f4cb31cd0babe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1737","number":1737,"commit":"cb91379caad315c23e20e0a80349e05ea6ef3fbd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1736","number":1736,"commit":"485d37fe37719f27cddc6dae481815e4b93e0670"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1733","number":1733,"commit":"9929323c98d0c813b1e984e8b5f70a7a5bd9f04d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1729","number":1729,"commit":"8fd24d295e3c39fcb7398421658917e8127825a3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1726","number":1726,"commit":"6bd75a6b459fc7aa11603f461a4be6a4a9bc0c50"}],"number":1745}
buildkite-pr-comment-->

2024-10-23 10:24 UTC, kaisecheng approved these changes
LGTM :)

2024-10-23 13:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1747)
* Commit: 3d5ab00cb8fe95d86774b089e056cf5e6a1aeb1e

### History
* :green_heart: [Build #1746](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1746) succeeded 8abc7935c2ca1f272d5c9d2a722a4c7c42162ecb
* :green_heart: [Build #1745](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1745) succeeded 2e90f147c6eab93f0e5123ec9b2f4cb31cd0babe
* :broken_heart: [Build #1737](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1737) failed cb91379caad315c23e20e0a80349e05ea6ef3fbd
* :green_heart: [Build #1736](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1736) succeeded 485d37fe37719f27cddc6dae481815e4b93e0670
* :green_heart: [Build #1733](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1733) succeeded 9929323c98d0c813b1e984e8b5f70a7a5bd9f04d
* :green_heart: [Build #1729](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1729) succeeded 8fd24d295e3c39fcb7398421658917e8127825a3

cc @andsel

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1747","number":1747,"commit":"3d5ab00cb8fe95d86774b089e056cf5e6a1aeb1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1746","number":1746,"commit":"8abc7935c2ca1f272d5c9d2a722a4c7c42162ecb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1745","number":1745,"commit":"2e90f147c6eab93f0e5123ec9b2f4cb31cd0babe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1737","number":1737,"commit":"cb91379caad315c23e20e0a80349e05ea6ef3fbd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1736","number":1736,"commit":"485d37fe37719f27cddc6dae481815e4b93e0670"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1733","number":1733,"commit":"9929323c98d0c813b1e984e8b5f70a7a5bd9f04d"}],"number":1747}
buildkite-pr-comment-->

2024-10-31 22:39 UTC, karenzone reviewed
Does this apply only to internal collection?  If so, we should call out  internal collection specifically.  Technically, any collection method we've used in the past would fall under the "legacy" umbrella, and we might need more precision and granularity than would be provided by labeling this one implementation as legacy. 
Please LMKWYT.

2024-11-04 08:07 UTC, andsel commented
@karenzone yes it's related just to the internal collector. Do you thing we should switch naming from `allow.legacy.monitoring` to `allow.internal.legacy.monitoring` ?

2024-11-05 16:27 UTC, andsel commented on .buildkite/scripts/benchmark/config/logstash.yml
> +allow.legacy:.monitoring: true
The problem we have with `xpack.monitoring.*` or `monitoring.*` is that
https://github.com/elastic/logstash/blob/5847d773311463e7450708f1b305ddc2b01fbe17/x-pack/lib/monitoring/monitoring.rb#L198-L200.

So we should have problems naming it `monitoring.enable_deprecated` but not if we name it `pack.monitoring.enable_deprecated`.

However we should put in the name the fact that it's "legacy" and is "internal", WDYT?

```
allow.legacy:.monitoring: true
```
yes my bad, typo switching from tree form yaml to single line

2024-11-13 17:42 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849)
* Commit: e8a2d72a8a2d07772b104311fc87a74e9a6981ad

### Failed CI Steps
* [:lab_coat: x-pack integration](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849#01932636-89b9-4bf1-a874-7d8fc9bcbe13)
* [:lab_coat: x-pack integration](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849#01932651-e1f9-4f2d-838f-2e6ec574edfc)
* [:lab_coat: x-pack integration](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849#0193266a-aa78-4c34-a9aa-fe3edd89f3c5)
* [:lab_coat: x-pack integration](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849#01932685-67f0-4712-bd02-b24b42e897c2)

### History
* :green_heart: [Build #1747](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1747) succeeded 3d5ab00cb8fe95d86774b089e056cf5e6a1aeb1e
* :green_heart: [Build #1746](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1746) succeeded 8abc7935c2ca1f272d5c9d2a722a4c7c42162ecb
* :green_heart: [Build #1745](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1745) succeeded 2e90f147c6eab93f0e5123ec9b2f4cb31cd0babe
* :broken_heart: [Build #1737](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1737) failed cb91379caad315c23e20e0a80349e05ea6ef3fbd
* :green_heart: [Build #1736](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1736) succeeded 485d37fe37719f27cddc6dae481815e4b93e0670
* :green_heart: [Build #1733](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1733) succeeded 9929323c98d0c813b1e984e8b5f70a7a5bd9f04d

cc @andsel

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849","number":1849,"commit":"e8a2d72a8a2d07772b104311fc87a74e9a6981ad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1747","number":1747,"commit":"3d5ab00cb8fe95d86774b089e056cf5e6a1aeb1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1746","number":1746,"commit":"8abc7935c2ca1f272d5c9d2a722a4c7c42162ecb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1745","number":1745,"commit":"2e90f147c6eab93f0e5123ec9b2f4cb31cd0babe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1737","number":1737,"commit":"cb91379caad315c23e20e0a80349e05ea6ef3fbd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1736","number":1736,"commit":"485d37fe37719f27cddc6dae481815e4b93e0670"}],"number":1849}
buildkite-pr-comment-->

2024-11-14 09:51 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1851)
* Commit: c0e0abafe05981f845da3dac07a6a0bb33512bf4

### Failed CI Steps
* [:lab_coat: Integration Tests / part 1](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1851#01932a14-72e6-4c8b-8ed1-63bd859a62db)
* [:lab_coat: Integration Tests / part 2](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1851#01932a14-72e8-4a15-bf49-e30889a2effc)
* [:lab_coat: IT Persistent Queues / part 2](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1851#01932a14-72ec-494b-8df6-b5e3b47f0d84)

### History
* :green_heart: [Build #1850](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1850) succeeded 20b2db2a7dd7e58fc6bf9805caf660d80e882bdd
* :broken_heart: [Build #1849](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849) failed e8a2d72a8a2d07772b104311fc87a74e9a6981ad
* :green_heart: [Build #1747](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1747) succeeded 3d5ab00cb8fe95d86774b089e056cf5e6a1aeb1e
* :green_heart: [Build #1746](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1746) succeeded 8abc7935c2ca1f272d5c9d2a722a4c7c42162ecb
* :green_heart: [Build #1745](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1745) succeeded 2e90f147c6eab93f0e5123ec9b2f4cb31cd0babe
* :broken_heart: [Build #1737](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1737) failed cb91379caad315c23e20e0a80349e05ea6ef3fbd

cc @andsel

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"running","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1851","number":1851,"commit":"c0e0abafe05981f845da3dac07a6a0bb33512bf4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1850","number":1850,"commit":"20b2db2a7dd7e58fc6bf9805caf660d80e882bdd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849","number":1849,"commit":"e8a2d72a8a2d07772b104311fc87a74e9a6981ad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1747","number":1747,"commit":"3d5ab00cb8fe95d86774b089e056cf5e6a1aeb1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1746","number":1746,"commit":"8abc7935c2ca1f272d5c9d2a722a4c7c42162ecb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1745","number":1745,"commit":"2e90f147c6eab93f0e5123ec9b2f4cb31cd0babe"}],"number":1851}
buildkite-pr-comment-->

2024-11-14 15:51 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1853)
* Commit: dcb0c250a94e66d95ee98f9cab8270c8731fce87

### History
* :yellow_heart: [Build #1851](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1851) was flaky c0e0abafe05981f845da3dac07a6a0bb33512bf4
* :green_heart: [Build #1850](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1850) succeeded 20b2db2a7dd7e58fc6bf9805caf660d80e882bdd
* :broken_heart: [Build #1849](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849) failed e8a2d72a8a2d07772b104311fc87a74e9a6981ad
* :green_heart: [Build #1747](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1747) succeeded 3d5ab00cb8fe95d86774b089e056cf5e6a1aeb1e
* :green_heart: [Build #1746](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1746) succeeded 8abc7935c2ca1f272d5c9d2a722a4c7c42162ecb

cc @andsel

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1853","number":1853,"commit":"dcb0c250a94e66d95ee98f9cab8270c8731fce87"},{"buildStatus":{"state":"passed","success":true,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1851","number":1851,"commit":"c0e0abafe05981f845da3dac07a6a0bb33512bf4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1850","number":1850,"commit":"20b2db2a7dd7e58fc6bf9805caf660d80e882bdd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849","number":1849,"commit":"e8a2d72a8a2d07772b104311fc87a74e9a6981ad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1747","number":1747,"commit":"3d5ab00cb8fe95d86774b089e056cf5e6a1aeb1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1746","number":1746,"commit":"8abc7935c2ca1f272d5c9d2a722a4c7c42162ecb"}],"number":1853}
buildkite-pr-comment-->

2024-11-15 15:45 UTC, karenzone commented on docs/static/monitoring/monitoring-internal-legacy.asciidoc
> +NOTE: Starting from version 9.0, legacy monitoring is deactivated and behind a feature flag. Set `xpack.monitoring.allow_legacy_collection` to `true` to allow access to the feature.
```suggestion
NOTE: Starting from version 9.0, legacy internal collection is behind a feature flag and is turned off by default. 
Set `xpack.monitoring.allow_legacy_collection` to `true` to allow access to the feature.

Using <<monitoring-with-ea,{agent} for monitoring>> is a better alternative for most {ls} deployments. 
```

2024-11-18 08:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1856)
* Commit: a5a202825267f8c84291e4cd873085355ae2eb20

### History
* :green_heart: [Build #1853](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1853) succeeded dcb0c250a94e66d95ee98f9cab8270c8731fce87
* :yellow_heart: [Build #1851](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1851) was flaky c0e0abafe05981f845da3dac07a6a0bb33512bf4
* :green_heart: [Build #1850](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1850) succeeded 20b2db2a7dd7e58fc6bf9805caf660d80e882bdd
* :broken_heart: [Build #1849](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849) failed e8a2d72a8a2d07772b104311fc87a74e9a6981ad
* :green_heart: [Build #1747](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1747) succeeded 3d5ab00cb8fe95d86774b089e056cf5e6a1aeb1e
* :green_heart: [Build #1746](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1746) succeeded 8abc7935c2ca1f272d5c9d2a722a4c7c42162ecb

cc @andsel

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1856","number":1856,"commit":"a5a202825267f8c84291e4cd873085355ae2eb20"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1853","number":1853,"commit":"dcb0c250a94e66d95ee98f9cab8270c8731fce87"},{"buildStatus":{"state":"passed","success":true,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1851","number":1851,"commit":"c0e0abafe05981f845da3dac07a6a0bb33512bf4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1850","number":1850,"commit":"20b2db2a7dd7e58fc6bf9805caf660d80e882bdd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1849","number":1849,"commit":"e8a2d72a8a2d07772b104311fc87a74e9a6981ad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1747","number":1747,"commit":"3d5ab00cb8fe95d86774b089e056cf5e6a1aeb1e"}],"number":1856}
buildkite-pr-comment-->

2024-11-18 18:36 UTC, karenzone approved these changes
LGTM

2024-11-19 07:52 UTC, merged