[Docremove modules doc
elastic/logstash pull request #16796
Opened 2024-12-13 14:41 UTC by kaisecheng

2024-12-13 14:45 UTC, kaisecheng commented on docs/static/deploying.asciidoc
> -https://www.elastic.co/blog/integrating-elastic-stack-with-arcsight-siem-part-1[blog series]
remove the link to module blog post

2024-12-16 17:29 UTC, robbavey commented
Let's work on this one with @karenzone before committing this removal - there are likely places where we will want to add placeholders to help users coming from previous documentation, and pointers to other elastic solutions to provide equivalent functionality

2024-12-16 17:40 UTC, karenzone commented
> Let's work on this one with @karenzone before committing this removal - there are likely places where we will want to add placeholders to help users coming from previous documentation, and pointers to other elastic solutions to provide equivalent functionality

Yes, please.  This is not how we handle doc removals.  I have two related issues to handle:
* #16590
* #16739

So maybe keep the change to

2024-12-16 17:41 UTC, karenzone requested changes
Docs require a different approach.  Please don't merge.

2025-01-07 14:33 UTC, closed without merging