remove enterprise search from default plugin
elastic/logstash pull request #16818
Opened 2024-12-19 13:32 UTC by kaisecheng

## Release notes

## What does this PR do?

## Why is it important/What is the impact to the user?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2024-12-19 13:58 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1978)
* Commit: 3e94a2a7d695ae7bcd163ed72ae3c1793ca0570b

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1978","number":1978,"commit":"3e94a2a7d695ae7bcd163ed72ae3c1793ca0570b"}],"number":1978}
buildkite-pr-comment-->

2024-12-19 14:48 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1979)
* Commit: 5b34e3716ac5e73974157fb4529db705a6bd7e17

### History
* :green_heart: [Build #1978](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1978) succeeded 3e94a2a7d695ae7bcd163ed72ae3c1793ca0570b

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1979","number":1979,"commit":"5b34e3716ac5e73974157fb4529db705a6bd7e17"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1978","number":1978,"commit":"3e94a2a7d695ae7bcd163ed72ae3c1793ca0570b"}],"number":1979}
buildkite-pr-comment-->

2024-12-19 16:44 UTC, donoghuc approved these changes
LGTM

2024-12-19 17:35 UTC, kaisecheng commented on docs/static/breaking-changes-90.asciidoc
> +For more details, visit: https://www.elastic.co/guide/en/enterprise-search/current/app-search-workplace-search.html
@flexitrev Is https://www.elastic.co/guide/en/enterprise-search/current/app-search-workplace-search.html the only page to point user about the product deprecation and transition? The instruction is a bit vague

2025-01-03 14:35 UTC, kaisecheng commented on docs/static/breaking-changes-90.asciidoc
> +For more details, visit: https://www.elastic.co/guide/en/enterprise-search/current/app-search-workplace-search.html
@karenzone I think the deprecation note is ready for review

2025-01-07 17:40 UTC, kaisecheng commented on docs/static/breaking-changes-90.asciidoc
> +For more details, please visit https://www.elastic.co/guide/en/search-ui/current/tutorials-elasticsearch.html
@karenzone Hope to get your review on deprecation note

2025-01-07 18:01 UTC, donoghuc requested changes

2025-01-07 18:01 UTC, donoghuc commented on .ruby-version
> +jruby-9.4.3.0
This looks like an unintended change, perhaps a bad merge conflict resolution? https://github.com/elastic/logstash/pull/16818/commits/ff5f491ce3e9cc5ae92c9d0864debb1b3aa57b77

2025-01-07 18:07 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2022)
* Commit: 117d8c4833e7df0ed21591d56ce850dba327d905

### History
* :green_heart: [Build #2003](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2003) succeeded 6ae878ccd96eb3710c90c7c6acee38da2df6b921
* :green_heart: [Build #1979](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1979) succeeded 5b34e3716ac5e73974157fb4529db705a6bd7e17
* :green_heart: [Build #1978](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1978) succeeded 3e94a2a7d695ae7bcd163ed72ae3c1793ca0570b

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2022","number":2022,"commit":"117d8c4833e7df0ed21591d56ce850dba327d905"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2003","number":2003,"commit":"6ae878ccd96eb3710c90c7c6acee38da2df6b921"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1979","number":1979,"commit":"5b34e3716ac5e73974157fb4529db705a6bd7e17"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1978","number":1978,"commit":"3e94a2a7d695ae7bcd163ed72ae3c1793ca0570b"}],"number":2022}
buildkite-pr-comment-->

2025-01-08 00:10 UTC, kaisecheng commented on .ruby-version
> +jruby-9.4.3.0
Oh thx ❤️

2025-01-08 00:37 UTC, donoghuc approved these changes

2025-01-08 00:37 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2024)
* Commit: d126a48b97920bce4c7c806e83924e1788d5b64a

### History
* :green_heart: [Build #2022](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2022) succeeded 117d8c4833e7df0ed21591d56ce850dba327d905
* :green_heart: [Build #2003](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2003) succeeded 6ae878ccd96eb3710c90c7c6acee38da2df6b921
* :green_heart: [Build #1979](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1979) succeeded 5b34e3716ac5e73974157fb4529db705a6bd7e17
* :green_heart: [Build #1978](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1978) succeeded 3e94a2a7d695ae7bcd163ed72ae3c1793ca0570b

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2024","number":2024,"commit":"d126a48b97920bce4c7c806e83924e1788d5b64a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2022","number":2022,"commit":"117d8c4833e7df0ed21591d56ce850dba327d905"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2003","number":2003,"commit":"6ae878ccd96eb3710c90c7c6acee38da2df6b921"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1979","number":1979,"commit":"5b34e3716ac5e73974157fb4529db705a6bd7e17"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1978","number":1978,"commit":"3e94a2a7d695ae7bcd163ed72ae3c1793ca0570b"}],"number":2024}
buildkite-pr-comment-->

2025-01-08 23:23 UTC, karenzone reviewed
I left a suggestion inline for your consideration.

2025-01-08 23:23 UTC, karenzone commented on docs/static/breaking-changes-90.asciidoc
> +For more details, please visit https://www.elastic.co/guide/en/search-ui/current/tutorials-elasticsearch.html
```suggestion
===== App Search and Workplace Search plugins are deprecated

Enterprise Search is deprecated and no longer supported from {stack} 9.0. 
We've also deprecated the {ls} App Search and Workplace Search plugins. 
These plugins will receive only security updates and critical fixes moving forward. 

We recommend using our native {es} tools for your Search use cases.
For more details, please visit https://www.elastic.co/guide/en/search-ui/current/tutorials-elasticsearch.html[Search UI with Elasticsearch].
```

2025-01-09 12:03 UTC, kaisecheng commented on docs/static/breaking-changes-90.asciidoc
> +For more details, please visit https://www.elastic.co/guide/en/search-ui/current/tutorials-elasticsearch.html
So much better ❤️

2025-01-09 12:15 UTC, merged

2025-01-09 12:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2031)
* Commit: 9d434b39607f21d9b69aa6272a533a2d079635f4

### History
* :green_heart: [Build #2024](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2024) succeeded d126a48b97920bce4c7c806e83924e1788d5b64a
* :green_heart: [Build #2022](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2022) succeeded 117d8c4833e7df0ed21591d56ce850dba327d905
* :green_heart: [Build #2003](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2003) succeeded 6ae878ccd96eb3710c90c7c6acee38da2df6b921
* :green_heart: [Build #1979](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1979) succeeded 5b34e3716ac5e73974157fb4529db705a6bd7e17
* :green_heart: [Build #1978](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1978) succeeded 3e94a2a7d695ae7bcd163ed72ae3c1793ca0570b

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2031","number":2031,"commit":"9d434b39607f21d9b69aa6272a533a2d079635f4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2024","number":2024,"commit":"d126a48b97920bce4c7c806e83924e1788d5b64a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2022","number":2022,"commit":"117d8c4833e7df0ed21591d56ce850dba327d905"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2003","number":2003,"commit":"6ae878ccd96eb3710c90c7c6acee38da2df6b921"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1979","number":1979,"commit":"5b34e3716ac5e73974157fb4529db705a6bd7e17"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1978","number":1978,"commit":"3e94a2a7d695ae7bcd163ed72ae3c1793ca0570b"}],"number":2031}
buildkite-pr-comment-->

2025-01-13 13:47 UTC, kaisecheng commented on docs/static/breaking-changes-90.asciidoc
> +===== App Search and Workplace Search plugins are deprecated
@karenzone Maybe we should use "removed" instead of "deprecated" to indicate the plugins will not come with Logstash 9