Respect environment variables in jvm.options
elastic/logstash pull request #16834
Opened 2024-12-24 18:44 UTC by kaisecheng

…bstituted with their corresponding values.

## Release notes

## What does this PR do?

## Why is it important/What is the impact to the user?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2024-12-24 19:16 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1990)
* Commit: 45b6e2d0454448db3fcae9008a55795cb7becee4

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1990","number":1990,"commit":"45b6e2d0454448db3fcae9008a55795cb7becee4"}],"number":1990}
buildkite-pr-comment-->

2024-12-30 17:52 UTC, donoghuc reviewed
I like that we skip this if we have a commented or empty line. Doing the regex on every "valid" line in config is probably low overhead in practice. Overall I think this will work for the majority of cases but it does have some requirements and edges that may be worth documenting. 

1. Spell out the highlights from the regexes `\$\{` `[A-Z_][A-Z0-9_]*` (mainly that the substitution must be in form `${FOO}` not `$FOO`, the name must be all caps and not start with an underscore etc `${FOO}` not `${foo}` and the default syntax). 
2. Nested substitution wont work `${ROOT:${LEAF}} `
3. Default values cannot have colons or dollar signs (i think this is relevant because we have an example of such in https://github.com/elastic/logstash/blob/01c8e8bb550f31ab89f68f6523431138d722dd50/config/jvm.options#L33 )
4. There is no escape characters (relates to 3)

2024-12-31 02:27 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1996)
* Commit: 90befd8eb2aef98a1dc9dc471327b7e1981d7468

### History
* :green_heart: [Build #1991](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1991) succeeded 70eb054db002a97c2bac91b8e46a867dbbf83c09
* :green_heart: [Build #1990](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1990) succeeded 45b6e2d0454448db3fcae9008a55795cb7becee4

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1996","number":1996,"commit":"90befd8eb2aef98a1dc9dc471327b7e1981d7468"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1991","number":1991,"commit":"70eb054db002a97c2bac91b8e46a867dbbf83c09"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1990","number":1990,"commit":"45b6e2d0454448db3fcae9008a55795cb7becee4"}],"number":1996}
buildkite-pr-comment-->

2024-12-31 02:28 UTC, kaisecheng commented
@donoghuc thanks for the edge case checking! I overlooked that we support lowercase variable and the $HOME in jvm.options.

Logstash has [documented](https://www.elastic.co/guide/en/logstash/current/environment-variables.html) about the dollar sign variable. $VAR is not the pattern Logstash support. Honestly the variables in jvm.options were interpreted in bash script which has different syntax to logstash env variable. Given that no reported issue on resolving the env var in jvm.options and it has been failing to resolve since 8.0, in this PR, I make it align to Logstash syntax. I noticed that we have different convention in [log4j](https://github.com/elastic/logstash/blob/main/config/log4j2.properties#L17). I will raise the question in weekly sync.

I updated the pattern to align to the current ruby [substitution](https://github.com/elastic/logstash/blob/main/logstash-core/lib/logstash/util/substitution_variables.rb#L26). We do not support nested variable

2025-01-02 20:29 UTC, kaisecheng commented
The variable name can start with lowercase, uppercase, underscore or dot `[a-zA-Z_.][a-zA-Z0-9_.]`

2025-01-02 20:47 UTC, donoghuc requested changes
So sorry, I was reviewing based on my local index. I had missed the newer commits. I dont think we should allow `.` in env var lookup. I do like allowing lowercase etc, but `.` does not make sense to me:

> Environment variable names used by the utilities in the Shell and Utilities volume of POSIX.1-2017 consist solely of uppercase letters, digits, and the <underscore> ( '_' ) from the characters defined in [Portable Character Set](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap06.html#tagtcjh_3) and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names. Uppercase and lowercase letters shall retain their unique identities and shall not be folded together. The name space of environment variable names containing lowercase letters is reserved for applications. Applications can define any environment variables with names from this name space without modifying the behavior of the standard utilities.

2025-01-02 20:47 UTC, donoghuc commented on tools/jvm-options-parser/src/main/java/org/logstash/launchers/JvmOptionsParser.java
> +    private static final Pattern ENV_VAR_PATTERN = Pattern.compile("\\$\\{([a-zA-Z_.][a-zA-Z0-9_.]*)(?::([^}]*))?\\}");
```suggestion
    private static final Pattern ENV_VAR_PATTERN = Pattern.compile("\\$\\{([a-zA-Z_][a-zA-Z0-9_]*)(?::([^}]*))?\\}");
```
Lets remove `.` as they are not in env var names? https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html

2025-01-03 13:56 UTC, kaisecheng commented on tools/jvm-options-parser/src/main/java/org/logstash/launchers/JvmOptionsParser.java
> +    private static final Pattern ENV_VAR_PATTERN = Pattern.compile("\\$\\{([a-zA-Z_.][a-zA-Z0-9_.]*)(?::([^}]*))?\\}");
We support`.` in env var, which is the same as Elasticsearch and the current Logstash.
For example, `docker run -d --name=es -p 9200:9200 -e "discovery.type=single-node" -e xpack.security.enabled=false -e xpack.security.http.ssl.enabled=false docker.elastic.co/elasticsearch/elasticsearch:8.17.0`

The moost important is we want to be consistent to the existing Logstash implementation. So, we should keep `.`

2025-01-03 17:14 UTC, donoghuc commented on tools/jvm-options-parser/src/main/java/org/logstash/launchers/JvmOptionsParser.java
> +    private static final Pattern ENV_VAR_PATTERN = Pattern.compile("\\$\\{([a-zA-Z_.][a-zA-Z0-9_.]*)(?::([^}]*))?\\}");
TIL. I didnt think that it was possible to set environment variables with dots in the names. I verified that if you can get it set (i tricked a bash shell in to doing it with `env`) java can in fact read it. 

```
➜  /tmp cat EnvVarDotTest.java
import java.util.Map;

public class EnvVarDotTest {
    public static void main(String[] args) {
        Map<String, String> env = System.getenv();
        env.forEach((key, value) -> {
            if (key.contains(".")) {
                System.out.println(key + "=" + value);
            }
        });
    }
}
➜  /tmp env test.var=hello java EnvVarDotTest
test.var=hello
```
Might be worth adding a test with a name that contains a dot. If nothing else but to alert that we do intend to support this (IMO kind of surprising) behavior.

2025-01-03 20:40 UTC, kaisecheng commented
@donoghuc can you approve this PR?

2025-01-03 20:46 UTC, donoghuc approved these changes
I think the implementation is correct.

Potential follow ons:
1. Do we need any specific docs describing the assumptions besides what is proposed for release notes?
2. Supporting env vars with `.` characters in them is somewhat surprising, can we add a test case for this as it seems like something easy to regress on if someone is looking at a regex that parses environment variables.

2025-01-03 21:48 UTC, donoghuc approved these changes
Thanks for the test addition!

2025-01-03 22:11 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2008)
* Commit: d41fa5a7c741b7323f595d9c3b98c175879b71a1

### History
* :green_heart: [Build #1996](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1996) succeeded 90befd8eb2aef98a1dc9dc471327b7e1981d7468
* :green_heart: [Build #1991](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1991) succeeded 70eb054db002a97c2bac91b8e46a867dbbf83c09
* :green_heart: [Build #1990](https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1990) succeeded 45b6e2d0454448db3fcae9008a55795cb7becee4

<!--buildkite-pr-comment-logstash-pull-request-pipeline
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/2008","number":2008,"commit":"d41fa5a7c741b7323f595d9c3b98c175879b71a1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1996","number":1996,"commit":"90befd8eb2aef98a1dc9dc471327b7e1981d7468"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1991","number":1991,"commit":"70eb054db002a97c2bac91b8e46a867dbbf83c09"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1990","number":1990,"commit":"45b6e2d0454448db3fcae9008a55795cb7becee4"}],"number":2008}
buildkite-pr-comment-->

2025-01-03 23:03 UTC, kaisecheng commented
We have only documented that logstash.yml supports the interpolation of environment variables. I can see we have never mentioned pipeline.yml and jvm.options support the same notation. 
We can improve the doc in a follow up issue, as I cannot find an immediate place to include the information.

2025-01-03 23:04 UTC, merged