Doc: Message Logstash module deprecations and removal
elastic/logstash pull request #16840
Opened 2024-12-27 22:14 UTC by karenzone

Related:
#16590
#16739

Messages deprecation of Logstash modules to preserve links and offer users a path forward with other options.

### Next steps @karenzone: 
* Set up redirects

2024-12-30 16:31 UTC, kaisecheng reviewed
All look good to me. I think we need to update the CEF part of [deploying and scaling Logstash](https://www.elastic.co/guide/en/logstash/current/deploying-and-scaling.html#_network_and_security_data) as it still points to a blog post of arcsight module. 

Maybe point it to CEF integration?

2025-01-02 16:23 UTC, robbavey requested changes
Pointer to more appropriate azure module replacement

2025-01-02 16:23 UTC, robbavey commented on docs/static/redirects.asciidoc
> +
The [Azure Event Hub integration](https://www.elastic.co/guide/en/integrations/current/azure-eventhub.html) is a more natural replacement - the Azure module for metricbeat is more for general azure process monitoring, whereas event hubs are the azure equivalent of Kafka. It is the Azure event hub plugin that the module works with

2025-01-03 20:05 UTC, robbavey commented on docs/static/redirects.asciidoc
> +diagnostic logs with the Elastic Stack.
I'm not sure if I'd keep the descriptive blurbs underneath. WDYT?

2025-01-03 22:03 UTC, karenzone commented on docs/static/redirects.asciidoc
> +diagnostic logs with the Elastic Stack.
I deleted a lot of text, but left the highlevel descriptions in to provide a bit of context.  If somebody has a link, sending them to a heading and a deprecation notice doesn't seem to be enough.

2025-01-03 22:19 UTC, robbavey commented on docs/static/redirects.asciidoc
> +diagnostic logs with the Elastic Stack.
Actually, looking further into it - https://www.elastic.co/guide/en/integrations/current/azure-events.html might be a better link - it seems much more comprehensive than the one I linked earlier, and does a lot more than our module does/did

@flexitrev WDYT?

2025-01-06 15:05 UTC, karenzone commented on docs/static/redirects.asciidoc
> +deprecated[7.8.0, "Replaced by the https://www.elastic.co/guide/en/integrations/current/azure-eventhub.html[Azure Event Hub integration]."]
```suggestion
deprecated[7.8.0, "Replaced by the https://www.elastic.co/guide/en/integrations/current/azure-events.html[Azure Logs integration]."]
```

2025-01-06 15:39 UTC, robbavey approved these changes
LGTM

2025-01-06 16:17 UTC, merged

2025-01-06 16:18 UTC, karenzone commented
19771